// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATMgdfmz9T_yBUR11xHqLXq_6CvWJoetk',
    appId: '1:877355377577:web:1a94ec0d4ad4f2066fdab8',
    messagingSenderId: '877355377577',
    projectId: 'analyticsdashboard-35573',
    authDomain: 'analyticsdashboard-35573.firebaseapp.com',
    storageBucket: 'analyticsdashboard-35573.firebasestorage.app',
    measurementId: 'G-5H1XCKSSQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNO6tR9Po5anbldtmZSS30XImDtj-x9aM',
    appId: '1:877355377577:android:a2189dbe52ab3ac66fdab8',
    messagingSenderId: '877355377577',
    projectId: 'analyticsdashboard-35573',
    storageBucket: 'analyticsdashboard-35573.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLtv3mqFoAA5VSZ1RtK1W5wEQzORjx6g',
    appId: '1:877355377577:ios:291ed4ecd590b3526fdab8',
    messagingSenderId: '877355377577',
    projectId: 'analyticsdashboard-35573',
    storageBucket: 'analyticsdashboard-35573.firebasestorage.app',
    iosBundleId: 'com.example.analyticsDashboard',
  );
}
